//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.26 at 09:41:33 PM CEST
//


package com.osa.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the io.spring.guides.gs_producing_web_service package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DestinationsRequest }
     *
     */
    public DestinationsRequest createDestinationsRequest() {
        return new DestinationsRequest();
    }

    /**
     * Create an instance of {@link HeartBeatRequest }
     *
     */
    public HeartBeatRequest createHeartBeatRequest() {
        return new HeartBeatRequest();
    }

    /**
     * Create an instance of {@link HeartBeatResponse }
     *
     */
    public HeartBeatResponse createHeartBeatResponse() {
        return new HeartBeatResponse();
    }

    /**
     * Create an instance of {@link Network }
     *
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link City }
     *
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Station }
     *
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link NetworkRequest }
     *
     */
    public NetworkRequest createNetworkRequest() {
        return new NetworkRequest();
    }

    /**
     * Create an instance of {@link OriginsRequest }
     *
     */
    public OriginsRequest createOriginsRequest() {
        return new OriginsRequest();
    }

    /**
     * Create an instance of {@link StationList }
     *
     */
    public StationList createStationList() {
        return new StationList();
    }

    /**
     * Create an instance of {@link Trip }
     *
     */
    public Trip createTrip() {
        return new Trip();
    }

    /**
     * Create an instance of {@link TripItem }
     *
     */
    public TripItem createTripItem() {
        return new TripItem();
    }

    /**
     * Create an instance of {@link TripRequest }
     *
     */
    public TripRequest createTripRequest() {
        return new TripRequest();
    }

    /**
     * Create an instance of {@link Coordinates }
     *
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Country }
     *
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Link }
     *
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Time }
     *
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link Transfer }
     *
     */
    public Transfer createTransfer() {
        return new Transfer();
    }

}
