//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.11 at 12:12:43 AM CEST 
//


package com.osa.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="searchBy" type="{http://spring.io/guides/gs-producing-web-service}searchBy" minOccurs="0"/>
 *         &lt;element name="fromCityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toCityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromStationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toStationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="adult" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="children" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bikes" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="currency" type="{http://spring.io/guides/gs-producing-web-service}currency" minOccurs="0"/>
 *         &lt;element name="departureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchBy",
    "fromCityId",
    "toCityId",
    "fromStationId",
    "toStationId",
    "adult",
    "children",
    "bikes",
    "currency",
    "departureDate"
})
@XmlRootElement(name = "tripRequest")
public class TripRequest {

    protected SearchBy searchBy;
    protected String fromCityId;
    protected String toCityId;
    protected String fromStationId;
    protected String toStationId;
    protected int adult;
    protected int children;
    protected boolean bikes;
    protected Currency currency;
    @XmlElement(required = true)
    protected String departureDate;

    /**
     * Gets the value of the searchBy property.
     * 
     * @return
     *     possible object is
     *     {@link SearchBy }
     *     
     */
    public SearchBy getSearchBy() {
        return searchBy;
    }

    /**
     * Sets the value of the searchBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchBy }
     *     
     */
    public void setSearchBy(SearchBy value) {
        this.searchBy = value;
    }

    /**
     * Gets the value of the fromCityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCityId() {
        return fromCityId;
    }

    /**
     * Sets the value of the fromCityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCityId(String value) {
        this.fromCityId = value;
    }

    /**
     * Gets the value of the toCityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCityId() {
        return toCityId;
    }

    /**
     * Sets the value of the toCityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCityId(String value) {
        this.toCityId = value;
    }

    /**
     * Gets the value of the fromStationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromStationId() {
        return fromStationId;
    }

    /**
     * Sets the value of the fromStationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromStationId(String value) {
        this.fromStationId = value;
    }

    /**
     * Gets the value of the toStationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToStationId() {
        return toStationId;
    }

    /**
     * Sets the value of the toStationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToStationId(String value) {
        this.toStationId = value;
    }

    /**
     * Gets the value of the adult property.
     * 
     */
    public int getAdult() {
        return adult;
    }

    /**
     * Sets the value of the adult property.
     * 
     */
    public void setAdult(int value) {
        this.adult = value;
    }

    /**
     * Gets the value of the children property.
     * 
     */
    public int getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     */
    public void setChildren(int value) {
        this.children = value;
    }

    /**
     * Gets the value of the bikes property.
     * 
     */
    public boolean isBikes() {
        return bikes;
    }

    /**
     * Sets the value of the bikes property.
     * 
     */
    public void setBikes(boolean value) {
        this.bikes = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCurrency(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDate(String value) {
        this.departureDate = value;
    }

}
